version: "3"
services:
  palm:
    image: palm
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18001:8000"
    volumes:
      - ./api:/palm/api
      - ./enums:/palm/enums
      - ./schemas:/palm/schemas
      - ./docs:/palm/docs
      - ./responses:/palm/responses
    environment:
      - PALM_SERVICE_NAME=palm
      - PALM_APP_ENVIRONMENT=test
      - PALM_LOG_LEVEL=DEBUG
      - PALM_ENABLE_CORS=true
      - PALM_CORS_ORIGINS=*
      - PALM_MONGO_HOST=mongodb-palm
      - PALM_MONGO_PORT=27017
      - PALM_MONGO_DB=palm
      - PALM_REDIS_HOST=redis-palm
      - PALM_REDIS_PORT=6379
      - PALM_REDIS_DB=0
      - PALM_REDIS_USERNAME=default
      - PALM_REDIS_PASSWORD=a1234a
      - PALM_FRONTEND_URL=http://localhost:18001
      - PALM_APP_VERSION=alpha
      - PALM_STORAGE_ACCESS_KEY=${PALM_STORAGE_ACCESS_KEY}
      - PALM_STORAGE_SECRET_KEY=${PALM_STORAGE_SECRET_KEY}
      - PALM_STORAGE_BUCKET_NAME=${PALM_STORAGE_BUCKET_NAME}
      - PALM_STORAGE_ENDPOINT=${PALM_STORAGE_ENDPOINT}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - PALM_AWS_CF_URL=${PALM_AWS_CF_URL}
      - PALM_APP_ACCESS_TOKEN_EXPIRE_MINUTES=${PALM_APP_ACCESS_TOKEN_EXPIRE_MINUTES}
      - PALM_APP_REFRESH_TOKEN_EXPIRE_MINUTES=${PALM_APP_REFRESH_TOKEN_EXPIRE_MINUTES}
      - PALM_APP_SECRET=${PALM_APP_SECRET}
      - PALM_APP_SECRET_ALGO=${PALM_APP_SECRET_ALGO}
      - PALM_GOOGLE_CLIENT_ID=${PALM_GOOGLE_CLIENT_ID}
      - PALM_GOOGLE_CLIENT_SECRET=${PALM_GOOGLE_CLIENT_SECRET}
      - PALM_KAKAO_CLIENT_ID=${PALM_KAKAO_CLIENT_ID}
      - PALM_KAKAO_CLIENT_SECRET=${PALM_KAKAO_CLIENT_SECRET}
      - PALM_GOOGLE_MAIL_APP_PASSWORD=${PALM_GOOGLE_MAIL_APP_PASSWORD}
      - PALM_GROQ_API_KEY=${PALM_GROQ_API_KEY}
      - PALM_EPSON_CLIENT_ID=${PALM_EPSON_CLIENT_ID}
      - PALM_EPSON_CLIENT_SECRET=${PALM_EPSON_CLIENT_SECRET}
      - PALM_EPSON_EMAIL_ID=${PALM_EPSON_EMAIL_ID}
    depends_on:
      mongodb-palm:
        condition: service_started
      redis-palm:
        condition: service_started
      minio-palm:
        condition: service_started
  proxy-palm:
    container_name: proxy-palm
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "18000:80"
    depends_on:
      - palm
