version: "3"
services:
  minio-palm:
    container_name: minio-palm
    image: minio/minio:RELEASE.2023-11-11T08-14-41Z
    restart: always
    ports:
      - 18003:9000
      - 18004:9001
    environment:
      MINIO_ROOT_USER: default
      MINIO_ROOT_PASSWORD: qwer1234
    command: server /data --console-address ":9001"
  minio-palm-client:
    container_name: minio-palm-client
    image: minio/mc:RELEASE.2023-11-10T21-37-17Z
    depends_on:
      - minio-palm
    entrypoint: >
      /bin/sh -c "
      mc alias set palm http://minio-palm:9000 default qwer1234 --api s3v4;
      mc mb palm/local;
      mc policy set public palm/local;
      exit 0;
      "
